Make dune build -p not require ppx_expect
ocurrent/ocluster pull request #139
Opened 2021-07-16 10:56 UTC by kit-ty-kate

```
$ dune build -p ocluster
File "test/dune", line 22, characters 19-29:
22 |   (preprocess (pps ppx_expect))
                        ^^^^^^^^^^
Error: Library "ppx_expect" not found.
```

2021-07-16 11:58 UTC, talex5 requested changes
The ocluster package depends on `ppx_expect`, so this should work if you've installed the dependencies (though it should be a just test dependency).

Removing this makes the API depend on the tests, which is not good.

2021-07-19 13:41 UTC, kit-ty-kate commented
> though it should be a just test dependency

well the issue currently is that it is not a test dependency:
```
$ dune build @install
File "test/dune", line 22, characters 19-29:
22 |   (preprocess (pps ppx_expect))
                        ^^^^^^^^^^
Error: Library "ppx_expect" not found.
Hint: try:
  dune external-lib-deps --missing @install
```

> Removing this makes the API depend on the tests, which is not good.

Are you sure? `dune build -p ocluster-api` works fine with this PR and without ppx_expect.

2021-07-19 14:00 UTC, talex5 commented
It's not just me. With your change, the CI is failing with:
```
current_ocluster.opam: changes needed:
  "capnp-rpc-lwt" {with-test & >= "1.2"}   [from scheduler]
  "capnp-rpc-net" {with-test & >= "1.2"}   [from scheduler]
  "lwt-dllist" {with-test & >= "1.0.1"}    [from scheduler]
  "ppx_expect" {with-test & >= "v0.14.1"}  [from test]
  "prometheus-app" {with-test & >= "1.1"}  [from test]
  "psq" {with-test & >= "0.2.0"}           [from scheduler]
  "sqlite3" {with-test & >= "5.0.3"}       [from db]
ocluster-api.opam: changes needed:
  "capnp-rpc-net" {with-test & >= "1.2"}   [from scheduler]
  "fmt" {with-test}                        [from db, test] (missing {with-test} annotation)
  "logs" {with-test & >= "0.7.0"}          [from scheduler, test]
  "lwt" {with-test}                        [from scheduler, test] (missing {with-test} annotation)
  "lwt-dllist" {with-test & >= "1.0.1"}    [from scheduler]
  "ppx_expect" {with-test & >= "v0.14.1"}  [from test]
  "prometheus" {with-test & >= "1.1"}      [from scheduler]
  "prometheus-app" {with-test & >= "1.1"}  [from test]
  "psq" {with-test & >= "0.2.0"}           [from scheduler]
  "sqlite3" {with-test & >= "5.0.3"}       [from db]
ocluster.opam: changes needed:
  "ppx_expect" {with-test}                 [from test] (missing {with-test} annotation)
```
This is because your change makes everything depend on the tests, which is not good.

But I don't understand how you don't have `ppx_expect`, when it's listed as a dependency in `ocluster.opam`.

2021-07-21 13:21 UTC, talex5 reviewed
Seems that what we want to do isn't currently possible - see https://github.com/ocaml/dune/issues/4738

2021-07-21 13:36 UTC, kit-ty-kate commented
ok then, closing. Hopefully dune can fix that at some point in the future.

2021-07-21 13:36 UTC, closed without merging